### PR TITLE
Download data from first 5 pages

### PR DESCRIPTION
**Pull request by dakk**
Offer the availability of more cryptocurrencies by parsing 5 pages of coins (500 coins)

### CODE REVIEW

**Comment by Nexuist** [comment]
Hi,

CoinMarketCap recently released their own API: https://coinmarketcap.com/api/

This should do what you want. I'm probably going to deprecate this project soon - I don't really see why you'd use this over CoinMarketCap's.

**Comment by dakk** [comment]
Hi Nexuist, I'm still using your APIs because coinmarketcap only offer the api ticker/:coinname while I need ticker/:symbol that you provide.
I could switch but your service is better for now ;)

**Comment by Nexuist** [comment]
Oh ok! Good to hear :)

Your PR looks fine. I'll just have to test it in my dev environment and push it out as soon as everything checks out. I'll let you know here.

**Comment by dakk** [comment]
Yea :+1:

**Comment by Nexuist** [comment]
Unfortunately what seemed like a simple change didn't really work out - I'd have to modify a bit more of the API than I assumed. Right now I'm focused on bringing the service back up, but maybe one day I'll look into this again.

**Pull request merged**
